const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.XML,
		C3.Behaviors.shadowcaster,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.ScriptsInEvents.FolhaJogo_Event20_Act2,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.shadowcaster.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.OnResume
	];
};
self.C3_JsPropNameTable = [
	{Mosaico: 0},
	{Mosaico2: 0},
	{Mosaico3: 0},
	{PlanoDeFundoEmBlocos: 0},
	{vidas: 0},
	{moedas: 0},
	{PulosRestantes: 0},
	{estado: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Pin: 0},
	{Cronômetro: 0},
	{PersonagemPrincipal: 0},
	{Teclado: 0},
	{Sólido: 0},
	{Terreno: 0},
	{Moedas: 0},
	{Sprite5: 0},
	{Direcao: 0},
	{vivo: 0},
	{Inimigo: 0},
	{SensorDireito: 0},
	{SensorEsquerda: 0},
	{Espinho1: 0},
	{Espinho2: 0},
	{Anchor: 0},
	{Vida: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{BotaoStart: 0},
	{FonteDeSprites: 0},
	{FonteDeSprites2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite6: 0},
	{Solid: 0},
	{ParedeAbismo: 0},
	{txtVidas: 0},
	{colisãoInimigo: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{colisão: 0},
	{Sprite: 0},
	{MoedaFixa: 0},
	{TiledBackground: 0},
	{SpriteFont: 0},
	{Mouse: 0},
	{Touch: 0},
	{txtMoedas: 0},
	{Âncora: 0},
	{Texto: 0},
	{Texto2: 0},
	{Sprite4: 0},
	{Sprite8: 0},
	{Áudio: 0},
	{Sprite7: 0},
	{FonteDeSprites3: 0},
	{Yes: 0},
	{No: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Texto3: 0},
	{BotaoJogarHistoria: 0},
	{XML: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Sprite9: 0},
	{txtParabens: 0},
	{ProjetorDeSombra: 0},
	{textVoltarAo: 0},
	{txtInício: 0},
	{portal: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PersonagemPrincipal: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Terreno: class extends self.ISpriteInstance {},
	Moedas: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	SensorDireito: class extends self.ISpriteInstance {},
	SensorEsquerda: class extends self.ISpriteInstance {},
	Espinho1: class extends self.ISpriteInstance {},
	Espinho2: class extends self.ISpriteInstance {},
	Vida: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	BotaoStart: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	FonteDeSprites2: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ParedeAbismo: class extends self.ISpriteInstance {},
	txtVidas: class extends self.ITextInstance {},
	colisãoInimigo: class extends self.ISpriteInstance {},
	colisão: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	MoedaFixa: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	txtMoedas: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	FonteDeSprites3: class extends self.ISpriteFontInstance {},
	Yes: class extends self.ISpriteFontInstance {},
	No: class extends self.ISpriteFontInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Texto3: class extends self.ITextInstance {},
	BotaoJogarHistoria: class extends self.ITextInstance {},
	XML: class extends self.IInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	txtParabens: class extends self.ITextInstance {},
	textVoltarAo: class extends self.ITextInstance {},
	txtInício: class extends self.ITextInstance {},
	portal: class extends self.ISpriteInstance {}
}